version: "3.1"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "33006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

  redis:
    image: redis:alpine3.12
    container_name: redis
    ports:
      - 6379
    networks:
      - mynetwork

  app:
    build: .
    container_name: app
    ports:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  web:
    build: ./.docker/nginx
    container_name: web
    restart: always
    environment:
      - APP_SERVICE_HOST=app
      - APP_SERVICE_PORT=9000
    ports:
      - "8000:80"
      - "3000:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:
    driver: local
